---
development:
  adapter: mysql2
  database: <%= ENV['STORE_NAME'] %>_dev
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['MYSQL_DB_PASSWORD'] %>
  host: <%= ENV['MYSQL_DB_HOST'] %>
  port: 3306

test:
  adapter: mysql2
  database: <%= ENV['STORE_NAME'] %>_test
  username: root
  encoding: utf8

production:
  adapter: mysql2
  database: <%= ENV['STORE_NAME'] %>_production
  pool: 5
  timeout: 5000
  username: root
  password: <%= ENV['MYSQL_DB_PASSWORD'] %>
  host: <%= ENV['MYSQL_DB_HOST'] %>
  port: 3306
